<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

	<!-- generator="WordPress/5.2.5" created="2019-12-14 07:36" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Foolstutorials</title>
	<link>http://localhost/foolstutorials</link>
	<description>Just another WordPress site</description>
	<pubDate>Sat, 14 Dec 2019 07:36:36 +0000</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://localhost/foolstutorials</wp:base_site_url>
	<wp:base_blog_url>http://localhost/foolstutorials</wp:base_blog_url>

		<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[ashish]]></wp:author_login><wp:author_email><![CDATA[ashishkvs@gmail.com]]></wp:author_email><wp:author_display_name><![CDATA[ashish]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

				
	<generator>https://wordpress.org/?v=5.2.5</generator>
<!--Page Generator !-->
<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "foolsrwn_java";

$table = "pyfunctions_ui";
// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
$sql = "SELECT * FROM $table "; //table from inclusion caller file
$result = $conn->query($sql);
//dynamic column
// $columns = ["Functions","Purpose"];

$conn->close();
// echo "connection closed";

$pageId=145;
// loop starts here 
 if ($result != null && $result->num_rows > 0) {
    // output data of each row
    while ($row = $result->fetch_assoc()) {
        $funcId = $row["funcid"];
        $pageName = $row["pagename"];
$url=$pageName;
$title = preg_replace("/[^A-Za-z0-9-]/", "-", $pageName);
$exampleTableName="pyexamples_ui";
//echo $title;
if($pageName !=null && $pageName !=''){
echo <<<WPPAGEGENERATOR
	
<item>
<title>$title</title>
<link>http://localhost/foolstutorials/$url</link>
<pubDate>Thu, 21 Dec 2019 06:55:43 +0000</pubDate>
<dc:creator><![CDATA[ashish]]></dc:creator>
<guid isPermaLink="false">http://localhost/foolstutorials/?page_id=$pageId</guid>
<description></description>
<content:encoded><![CDATA[<!-- wp:paragraph -->
<p>$exampleTableName $funcId</p>
<!-- /wp:paragraph -->]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>$pageId</wp:post_id>
<wp:post_date><![CDATA[2019-12-12 06:55:43]]></wp:post_date>
<wp:post_date_gmt><![CDATA[2019-12-12 06:55:43]]></wp:post_date_gmt>
<wp:comment_status><![CDATA[closed]]></wp:comment_status>
<wp:ping_status><![CDATA[closed]]></wp:ping_status>
<wp:post_name><![CDATA[$url]]></wp:post_name>
<wp:status><![CDATA[publish]]></wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type><![CDATA[page]]></wp:post_type>
<wp:post_password><![CDATA[]]></wp:post_password>
<wp:is_sticky>0</wp:is_sticky>
												<wp:postmeta>
<wp:meta_key><![CDATA[_wp_page_template]]></wp:meta_key>
<wp:meta_value><![CDATA[page-reference-example.php]]></wp:meta_value>
</wp:postmeta>
</item>

WPPAGEGENERATOR;
$pageId++;
	}
	}
}


?>
</channel></rss>